# Generated by Django 4.0.5 on 2022-06-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=25, unique=True)),
                ('puntaje_Total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=500)),
                ('categ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='SimpQuizApp.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=150, verbose_name='Respuesta')),
                ('correcta', models.BooleanField(default=False)),
                ('preg_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre', to='SimpQuizApp.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ronda', models.CharField(max_length=20)),
                ('puntaje_Ronda', models.IntegerField(default=0)),
                ('participanteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partiId', to='SimpQuizApp.participante')),
                ('preguntaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunId', to='SimpQuizApp.preguntas')),
            ],
        ),
    ]
